### ISSUE TITLE
What gmail account is it uploading to is not visible on the GUI? How to change it is not there either?

### ISSUE THREAD

**Issue by nobodytooo** [ylexus/jiotty-photos-uploader#110]
How do I know to what account did I point the uploader? GUI does not show it.
How do I change the gmail account?
Do you know how to check which of my Pixels is attached to which gmail account? Google is not helpful at all.

**Comment by ylexus** [comment]
For now, it's impossible to see in the app which account you're logged in to. You'll have to log out via menu and log back in to make sure.
I will try improving the app to show this.

**Comment by ylexus** [comment]
I don't own any Android phones so can't comment on Pixels.

**Comment by nobodytooo** [comment]
Spasiba Alyosha.
Luc

**Comment by ylexus** [comment]
Added the logout button to the folder selection screen. Google API does not disclose user's email address, so I can't display it to show which account is in use. This is the best I can do, should be enough!

**Comment by nobodytooo** [comment]
Thank you. It solves the problem in that I do not have to shut down the program to be able to re-log where I want.

**Comment by ylexus** [comment]
As I mentioned in the previous comment, you did not have to shut down earlier either - the logout option has always been available in the menu.
