### ISSUE TITLE
DS_Store should be .DS_Store

### ISSUE THREAD

**Issue by huyz** [ylexus/jiotty-photos-uploader#112]
A dot is missing in `.DS_Store` here (and in the test files):

```java
private static final String P_DS_STORE = "glob:**/DS_Store";
```

**Comment by ylexus** [comment]
Indeed, thanks. I'll fix it once I finish with the current big chunk of work.

**Comment by ylexus** [comment]
Done, existing entry in preferences mentioning the  invalid pattern will be auto-migrated on running the new version.
