### ISSUE TITLE
Some photos are uploaded with out thier taken date. instead, the upload date is set as photo date.

### ISSUE THREAD

**Issue by yosigolan** [ylexus/jiotty-photos-uploader#124]
See example of folder structure (and photos) that created this issue:
[Tests1.zip](https://github.com/ylexus/jiotty-photos-uploader/files/9384722/Tests1.zip)

Try uploading the root folder.
i tried both upload modes but both give same results.

**Comment by ylexus** [comment]
The files you sent do not have any dates in their EXIF metadata - see https://github.com/ylexus/jiotty-photos-uploader/wiki#limitations, item 3.

**Comment by yosigolan** [comment]
@ylexus , i don't understand why you say that. for the image "תמומות מאייפון 29.1.14 073.JPG" this is what i see:
ExifTool Version Number         : 12.44
File Name                       : ·εσεσ· εαΘΘ⌠σ∩ 29.1.14 073.JPG
Directory                       : C:/Users/Zohar/OneDrive/Tests1/TestFolder1
Warning                         : FileName encoding not specified
File Size                       : 116 kB
File Modification Date/Time     : 2013:06:12 21:45:19+03:00
File Access Date/Time           : 2022:08:20 22:44:41+03:00
File Creation Date/Time         : 2022:08:19 16:16:36+03:00
File Permissions                : -rw-rw-rw-
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Big-endian (Motorola, MM)
Orientation                     : Horizontal (normal)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Y Cb Cr Positioning             : Centered
Exif Version                    : 0221
Components Configuration        : Y, Cb, Cr, -
Flashpix Version                : 0100
Color Space                     : sRGB
Exif Image Width                : 800
Exif Image Height               : 597
Scene Capture Type              : Standard
XP Keywords                     : ╫¬╫₧╫ץ╫₧╫ץ╫¬ ╫₧╫נ╫ש╫ש╫ñ╫ץ╫ƒ 29.1.14
Padding                         : (Binary data 2060 bytes, use -b option to extract)
Compression                     : JPEG (old-style)
Thumbnail Offset                : 4502
Thumbnail Length                : 5120
About                           : uuid:faf5bdd5-ba3d-11da-ad31-d33d75182f1b
Date Acquired                   : 2014:01:29 21:38:58.791
Last Keyword XMP                : ╫¬╫₧╫ץ╫₧╫ץ╫¬ ╫₧╫נ╫ש╫ש╫ñ╫ץ╫ƒ 29.1.14
Subject                         : ╫¬╫₧╫ץ╫₧╫ץ╫¬ ╫₧╫נ╫ש╫ש╫ñ╫ץ╫ƒ 29.1.14
Image Width                     : 800
Image Height                    : 597
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 800x597

**Comment by ylexus** [comment]
@yosigolan there are no dates in EXIF. The three dates you see there are filesystem dates/times, that is, when the **file** was created and modified, not when the picture was taken. If you use same tool on an image from your smartphone, you’ll see additional date, something like “date taken”. 
The rest is explained on the wiki website
