### ISSUE TITLE
App Closes immediately in Macbook M1

### ISSUE THREAD

**Issue by RookieAtCoding** [ylexus/jiotty-photos-uploader#130]
I basically know nothing about coding. I installed the dmg file and it ran perfectly fine. I created an API token in Google website, and when I put it into my app it just stopped, and I tried and uninstalling and installing it multiple times. Even tried installing in a new directory, but still it wasn't working.

**Comment by RookieAtCoding** [comment]
Found a solution.  

Go to your user directory and delete the folder named .jiottyphotosuploader. It is a hidden folder.

**Comment by RookieAtCoding** [comment]
Solved

**Comment by ylexus** [comment]
It shouldn't work on Apple processors at all. As far as I remember, some of the google connectivity libraries I use include natively compiled binaries for a subset of platforms and Apple ARM is not one of them. I will be mighty surprised if it uploads anything successfully on an Apple Silicon Mac.
