### ISSUE TITLE
Add tip to detail what happens in event of failures

### ISSUE THREAD

**Issue by nikc0069** [ylexus/jiotty-photos-uploader#21]
Great piece of software, but it isn't clear whether failures stop upload of photos, or whether the api limit has been hit. Uploads appear to have stopped but I don't k ow whether to wait or whether a failure has  caused them to stop.

**Comment by ylexus** [comment]
@nikc0069, can I ask which version do you use? The latest (1.0.3) does add a clear flashing hint when you hit the API limit. Also, it adds a report about all the failures when you click on “Failures”.

**Comment by nikc0069** [comment]
@ylexus yup 1.0.3 and the warning are great. I only get them on the stages prior to the upload though. I've since learned that even with failures it will carry on. I'm not sure if the failures link means the flashing warning doesn't show on the upload stage. Now I know it's not a biggie but I stopped and resumed as I wasn't sure whether the failure had stopped the whole upload process.

**Comment by ylexus** [comment]
I’m working on better use of batch upload requests (#17)  which will hopefully reduce the probability of API limit hits as the limits are shared by everyone. 

I’ll probably also add a clear indication/hint that failures are not blocking the progress by themselves.

**Comment by nikc0069** [comment]
@ylexus Great stuff. Thank you! Great piece of software.
