### ISSUE TITLE
Add support for High quality instead of Original full resolution

### ISSUE THREAD

**Issue by liliandjeff** [ylexus/jiotty-photos-uploader#22]
Looks like the upload is original full resolution.  My Google Photos account setting is High quality (free unlimited storage).  Getting error INVALID_ARGUMENT: The remaining storage in the user's account is not enough to perform this operation.

Can you honor the upload setting or provide a Jiotty setting for upload resolution?  Thanks

**Comment by grantpinkerton** [comment]
Hello - I may be wrong, but I also ran into this problem and when I looked into it, it would appear that the Google API that facilitates the upload only allows original full resolution uploads. I had to follow the below instructions to compress any images uploaded. I was uploading a lot of images so for me it was easier to buy 100gb of space for a month, upload everything i needed, compress the images every day and then cancel my 100gb subscription. Hope that helps

How to Recover Storage on Google Photos

1. Go to photos.google.com, and click on the hamburger menu after signing in with the account.
2. Click on Settings, and switch to High Quality.
3. As soon as you do that, you will see a prompt “Recover XYZ.abc GB of storage by also compressing existing items (this can’t be undone).”
4. Check the box and click on the Confirm button.
5. Google Photos will start reducing the size of the photo of the uploaded images to match with High Quality.
6. You should see a message, “Compressing photos & videos to high quality.”

Depending on the size of the images and videos uploaded in Original quality, it may take time. You can close the windows and come back later to check how much storage was recovered. You can note down the amount of storage space left, which is available with the Original radio button option.

Note: You can only restore storage once a day.

**Comment by liliandjeff** [comment]
Thanks for the suggestions and quick response

**Comment by ylexus** [comment]
@grantpinkerton thanks for the response to @liliandjeff. I'll reopen this issue to at least make it clearer in the app that the originals are always uploaded. The app already warns at the bottom that the the uploads will count towards the Google storage, but perhaps the warning could be more pronounced and worded clearer.
