### ISSUE TITLE
Failed to launch JVM

### ISSUE THREAD

**Issue by thebest07111** [ylexus/jiotty-photos-uploader#24]
Hello,

Whenver I try to start the windows 10 app (I am on windows 10) it shows me an failed to launch JVM error:
![failed to launch jvm](https://user-images.githubusercontent.com/9769181/80301768-5ba3be00-87a6-11ea-8afa-0a45ed2eb3dd.PNG)
[main.log](https://github.com/ylexus/jiotty-photos-uploader/files/4534894/main.log)

**Comment by ylexus** [comment]
@thebest07111 thanks, this is easily fixable, this happens because you’ve got Dutch as the main system language and I only tested with English and Russian :-). A shameful bug. I’ll fix and release a new version ASAP.

**Comment by ylexus** [comment]
Fixed in 1.0.5.
