### ISSUE TITLE
Fails to upload a folder with more than 50 images

### ISSUE THREAD

**Issue by grantpinkerton** [ylexus/jiotty-photos-uploader#26]
Tested using Windows 10. Version 1.0.6

When I try an upload a folder with over 50 images I get this error for each of the files:

C:\PHOTOGRAPHS\ALBUM_NAME\FILE_NAME.JPG	INVALID_ARGUMENT: Request must have less than 50 items.

**Steps to reproduce:**

1)Create folder A with 70 images
2)Try to upload the folder A
3)Fails with the error INVALID_ARGUMENT: Request must have less than 50 items. --however Album A is created in Google photos, it is just empty
4)Move 30 of the images from folder to folder B (folder A now has 40 images)
5)Try and upload folder A
5)This should be successful - the album on Google photos now has 40 images
6)Move the 30 images from folder B back into folder A (folder A now has all 70 images)
7)Try to upload folder A
8)Should fail with the error INVALID_ARGUMENT: Request must have less than 50 items.
9)Remove from folder A the 40 images that successfully uploaded under point 5 (folder A now has 30 images)
10)Try and upload folder A
11)This should be successful - the album on Google photos now has all 70 images

**Comment by ylexus** [comment]
Ha, this is something I wanted to test but miserably failed. It’s a regression in 1.0.4. Please use version 1.0.3 for now. I’ll fix today.

**Comment by ylexus** [comment]
Fixed in 1.0.7
