### ISSUE TITLE
Upload pictures as degraded quality ?

### ISSUE THREAD

**Issue by skylow48** [ylexus/jiotty-photos-uploader#29]
Is there a way to upload pictures as degraded quality, to don't have any space restriction (unlimited free storage) ?

**Comment by ylexus** [comment]
@skylow48 Unfortunately not. Google Photos API does not support this. So all media uploaded will be in original resolution and so will take up space in your Google Account. I've added this to the FAQ

**Comment by ylexus** [comment]
https://developers.google.com/photos/library/guides/upload-media: 
> Note: All media items uploaded to Google Photos through the API are stored in full resolution at original quality.
