### ISSUE TITLE
Order of items in albums

### ISSUE THREAD

**Issue by wheleph** [ylexus/jiotty-photos-uploader#31]
Uploaded photos are displayed in Google Photos album in some inconsistent order. They are definitely not ordered by date (which is the case when one uses native Google Photos UI to do it).

IMHO it would be natural to sort the photos by date in create albums. Maybe this is another limitation of Google Photos API? Then it's worth mentioning it in Wiki.

Affected version: 1.0.8

**Comment by ylexus** [comment]
It looks like this may actually be possible, if I separate the uploading and adding to the album stages. This is because once the item is uploaded, I can get hold of its metadata, and creation date/time is one of them. Let me experiment with the API.

**Comment by ylexus** [comment]
OK I've made it work. It's an emulation as the order in the album depends on the order of items in the API request. Google Photos does not re-order items uploaded via API. As a result, the order is not guaranteed, for example, when the upload is cancelled in an unlucky moment and re-tried, the order may be broken. The probability of that is quite small though, so current implementation will have to do for now.

It'll be released in whatever version is coming next (planning on 1.1.0).

**Comment by wheleph** [comment]
Thank you very much!

This is an awesome piece of software by the way!

**Comment by ylexus** [comment]
[1.1.0 is released](https://github.com/ylexus/jiotty-photos-uploader/releases/tag/1.1.0)

**Comment by wheleph** [comment]
I confirm that the order of items is correct now.
