### ISSUE TITLE
Date change to today with large video file

### ISSUE THREAD

**Issue by axylee** [ylexus/jiotty-photos-uploader#32]
The date will change to today with Jiotty , tested below steps : 
1: upload to GP manually within the web browser , the file size and date is correct .
2: delete and clean up the bin .
3: upload to GP the same video with Jiotty uploader , the file size the same , but the date change to today .
1-test file size in explorer
![1-test file size in explorer](https://user-images.githubusercontent.com/65884869/82780930-2664bb80-9e8b-11ea-8c86-32a0fdb94891.JPG)

2-manual upload to GP
![2-manual upload to GP](https://user-images.githubusercontent.com/65884869/82780935-2cf33300-9e8b-11ea-8a5b-f930eb7b49a5.JPG)

3-data size and date is correct
![3-data size and date is correct](https://user-images.githubusercontent.com/65884869/82780942-311f5080-9e8b-11ea-8793-dd468cd8a814.JPG)

4-date change with Jiotty
![4-date change with Jiotty](https://user-images.githubusercontent.com/65884869/82780948-35e40480-9e8b-11ea-96f4-097da5bebebe.JPG)

**Comment by axylee** [comment]
i have done some more test and found : 
1: upload with web browser to GP , the date will first fetch the info " Media Created " , if there is no info then fetch the file " Date Modified " info as taken date .
2: upload with Jiotty uploader , the video date will only fetch the " Media Created " info as video taken date , if the file comes with no info , then will use upload time as taken date . As the result , some of the video file with no " Media Created " info , the taken date will become today on GP .

Please close this issue if the finding is satisfy .

**Comment by ylexus** [comment]
@axylee I was about to reply with the same, but you've nailed it. Jiotty does not pay attention to the file's modification date/time in the file system. In fact, there is no place in the Google Photos API to override the file's date / time. The API allows you to specify the file bytes, file name and description - and that's all. Therefore the date/time is taken from the file's contents (EXIF or similar metadata), not the file's modification date in your file system. So unfortunately, there is no way to make it work like manual upload in this regard.

I actually had almost the same problem with a lot of my videos. What I've done is I wrote a script that used third-party software to add metadata to each file. In my case they were vide files in Matroska format. In your case it seems to be .mov files. It looks like https://exiftool.org can do the job for you, but you need to be good with basic scripting.

**Comment by axylee** [comment]
@ylexus Thank you for your reply , and once again , such a great APP you create . in further found the info fetching for picture file , i think its better to write here for the other Jiotty lovers to know:
.mov  => only fetch " Media Created " data as date .
.jpg    => only fetch " Date taken " data as date .
.png   => only fetch " Date taken " data as date .
the other format of file which not support above data will mark as upload time , this is under Windows 10 explorer , not sure about Mac or Linux will have this data read or not .

**Comment by ylexus** [comment]
@axylee I've updated the Limitations section on the wiki: https://github.com/ylexus/jiotty-photos-uploader/wiki#limitations. The key here is not the format of the file, but whether the file's EXIF or similar metadata has been retained or lost. By the way, how did you create those MOV files so that they ended up without metadata?

**Comment by axylee** [comment]
@ylexus some of those .MOV file without metadata was transfer from my Nikon camera to PC , i'm not sure where went wrong , but most of them only has the " Modify date " of file which match the actual taken date , and without " Media Created " metadata . The others was taken by iphone which are fine .
