### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by ylexus** [ylexus/jiotty-photos-uploader#37]
To help with translation, please have a look at this file: https://github.com/ylexus/jiotty-photos-uploader/blob/master/src/main/resources/i18n/Resources.properties. It contains all the phrases needed by the app. The file is in the format:

key=phrase

There are also some clarifying comments in the file that start with '#' - these explain some context for the key that follows, but do not need to be translated. 

@axylee, there are two options:
1. if you are familiar with git and GitHub, you could just create two copies of this file in same directory and submit a pull request.
2. if you are not familiar with git, please copy-paste the contents of the file above here twice in two different comments and in each comment replace the English text after the "=" with the corresponding Chinese phrase?

Thanks again for agreeing to help!

**Comment by axylee** [comment]
I had add one file in i18n and pull request , please have a look , and let me know if I am do wring .

**Comment by axylee** [comment]
Created 9 files , and pull request , not sure if the file name format is work for this code , please verify , thank you.
-----Chinese Traditional-----
Resources_zh_TW.properties
Resources_zh-CHT.properties
Resources_zh-HK.properties
Resources_zh-HANT.properties
Resources_zh-MO.properties


-----Chinese Simplified-----
Resources_zh-CHS.properties
Resources_zh-CN.properties
Resources_zh-HANS.properties
Resources_zh-SG.properties

**Comment by ylexus** [comment]
Thanks, I did not expect you to create pull requests - excellent! Even better if it was one pull request for all 9 files instead of 9 different ones :) But that's ok, next time maybe. I'll add comments to only some of them.

**Comment by ylexus** [comment]
Thanks, all merged, will be in the next release. Huge thanks for your help!

**Comment by ylexus** [comment]
@axylee, [1.2.0](https://github.com/ylexus/jiotty-photos-uploader/releases/tag/1.2.0) is now available with your translation and few bugfixes around the stop button. Thanks for your contribution!

**Comment by axylee** [comment]
Both Traditional and simplified Chinese are display fine !  and upload seems more smooth on 1.2.0 . If there is additional feature need to test or translate in the future, please feel free to let me know . 

![image](https://user-images.githubusercontent.com/65884869/84609041-c9877e80-aee7-11ea-8c79-e953efb09beb.png)

![image](https://user-images.githubusercontent.com/65884869/84609252-cfca2a80-aee8-11ea-9013-8a4a112a45ed.png)
