### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by Faxanadu2** [ylexus/jiotty-photos-uploader#47]
Hello, thanks for releasing this app, it's very useful batch upload photos onto a google photos. I do however have some concerns about uploading thousands and thousands of pictures to Google photos via this API. What is the level of privacy that you can offer i.e.  the app will not store users' photos and personal data? Thank you so much.

**Comment by ylexus** [comment]
@Faxanadu2, the app simply reads the files from the disk and passes them directly to Google Photos API. It also stores file names in the config file in your home directory to support resumed uploads. It does not do anything else to your data. Please read the [Privacy Policy](https://github.com/ylexus/jiotty-photos-uploader/wiki/Privacy-Policy): The Google Photos API is written by Google, so Google Privacy Policy applies too.
