### ISSUE TITLE
Allow specifying white list of folders/files

### ISSUE THREAD

**Issue by ylexus** [ylexus/jiotty-photos-uploader#62]
On the back of https://www.exler.ru/likbez/google-photos-kak-polzovatsya-i-vsyakiye-khitrosti.htm#nuzu

**Comment by ylexus** [comment]
@axylee thanks for helping the project with translation! Some more work or you - if you check all Chinese resources, I've added #TODO translate tokens before each phrase that needs translation. Could you work on these please? 
Also always wanted to ask: do you think it is enough to have zh_HANS and zh_HANT, and remove the rest?

**Comment by axylee** [comment]
> @axylee thanks for helping the project with translation! Some more work or you - if you check all Chinese resources, I've added #TODO translate tokens before each phrase that needs translation. Could you work on these please?
> Also always wanted to ask: do you think it is enough to have zh_HANS and zh_HANT, and remove the rest?
For what i know , zh_HANS and zh_HANT are the new tag , most of system may not recognize yet , it's good to keep the others until we tested on all supported platform .

**Comment by ylexus** [comment]
Released in [1.4.0](https://github.com/ylexus/jiotty-photos-uploader/releases/tag/1.4.0)
