### ISSUE TITLE
Report explicit error if incompatible config format is detected

### ISSUE THREAD

**Issue by ylexus** [ylexus/jiotty-photos-uploader#65]

**Comment by ylexus** [comment]
So that this does not happen:
[main.log](https://github.com/ylexus/jiotty-photos-uploader/files/4976277/main.log)

**Comment by ylexus** [comment]
@axylee could you translate a single phrase please that I added for this issue? Not that I found a way to remove the resource file duplication; there is now only two files: HANS and HANT. All the other locales that you added will be automatically forwarded to one of these two. Easier for you!

**Comment by axylee** [comment]
> @axylee could you translate a single phrase please that I added for this issue? Note that I found a way to remove the resource file duplication; there is now only two files: HANS and HANT. All the other locales that you added will be automatically forwarded to one of these two. Easier for you!

LoL , you are the man !  Done translate and pull request .

**Comment by ylexus** [comment]
Fixed in [1.4.1](https://github.com/ylexus/jiotty-photos-uploader/releases/tag/1.4.1)

**Comment by axylee** [comment]
> @axylee could you translate a single phrase please that I added for this issue? Note that I found a way to remove the resource file duplication; there is now only two files: HANS and HANT. All the other locales that you added will be automatically forwarded to one of these two. Easier for you!

Seems the local re-direction not work .
![image](https://user-images.githubusercontent.com/65884869/88616351-8dd6fb80-d0c6-11ea-9818-44f2f546d30d.png)

**Comment by ylexus** [comment]
@axylee what is your windows display language in language settings?

**Comment by ylexus** [comment]
@axylee and preferred languages?

**Comment by ylexus** [comment]
@axylee apparently HANS and HANT have to be named as Hans and Hant. Fixed now in [1.4.2](https://github.com/ylexus/jiotty-photos-uploader/releases/tag/1.4.2). CHS/CHT are still not properly forwarded in 1.4.2. Will fix in future versions, don't think it's urgent.

**Comment by axylee** [comment]
> @axylee what is your windows display language in language settings?

My is Chinese Taiwan , should be zh_TW , which is Chinese traditional .

**Comment by axylee** [comment]
> @axylee apparently HANS and HANT have to be named as Hans and Hant. Fixed now in [1.4.2](https://github.com/ylexus/jiotty-photos-uploader/releases/tag/1.4.2). CHS/CHT are still not properly forwarded in 1.4.2. Will fix in future versions, don't think it's urgent.

Its work now , in 1.4.2

![image](https://user-images.githubusercontent.com/65884869/88908058-ffac7200-d28b-11ea-9c2f-f674b1472943.png)

**Comment by ylexus** [comment]
Thanks for checking! I verified too by setting Windows interface language to Hong Kong SAR, which for some reason resulted in zh_TW_#Hant locale (was expecting zh_HK_#Hant). But whatever, it's the same thing anyway and it works.
