### ISSUE TITLE
another copy of the app is already running - error

### ISSUE THREAD

**Issue by RickyCox** [ylexus/jiotty-photos-uploader#69]
Hi. I’ve been using your great utility for a week or so and its been working fine.
But when I came to run it today, I got this error mgs: 
another copy of the app is already running
so I looked in Task manager, and I could not see any evidence of this. So I rebooted and still got the same msg when I restarted. I’ve uninstalled and reinstalled, tried removing all references to Jiotty photos uploader from regedit, restarted, reinstalled and still get this msg.
I’m now at the end of my own problem-solving skills.
Any chance of some help / guidance please?
Richard

**Comment by ylexus** [comment]
Can I ask you to try running the app, get the error, click OK in that dialog, and then attach here the log file - `%USERPROFILE%\.jiottyphotosuploader\log\main.log`?

**Comment by RickyCox** [comment]
Hi Alexey

Thanks for your quick support response.

 

I ran the program today and it would not reproduce the error dialogue – nothing appeared to happen

So I attach 2 logs: from today and also from 2 days ago when I was getting the “another copy of the app is already running” error.

 

Regards Richard

**Comment by ylexus** [comment]
Hi, it seems like you replied to the email and that added a reply to this GitHub issue, which I didn’t know you could do! Unfortunately, the attachments were lost. Could you just open this issue on github website and drag the files onto the comment box so that they are attached to the issue, instead of attaching to the reply to the notification email?

**Comment by RickyCox** [comment]
Hi. I had to add a .txt extension before GitHub would accept these files. R

[main.log.2020-08-10-06-02.txt](https://github.com/ylexus/jiotty-photos-uploader/files/5062520/main.log.2020-08-10-06-02.txt)


[main.log.txt](https://github.com/ylexus/jiotty-photos-uploader/files/5062512/main.log.txt)

**Comment by ylexus** [comment]
The file with the date is the normal upload session, no problems there, this file is from the times when the app was working. The other one indicates a corrupted database/config file. Would you be able to email me this file `%USERPROFILE%\.jiottyphotosuploader\data.json` to alexey@yudichev.net? Reason I am asking to email is that this file may contain your file names which you may consider private. 
AFTER you emailed it to me, can you try deleting this file and starting again, and let me know what happens? The app will forget what it’s uploaded unfortunately, but this is safe as Google Photos will not create duplicates.

**Comment by ylexus** [comment]
@RickyCox, are you still interested in this? The only conclusion I can make from the logs is that there's a possibility for the database to be corrupted, and to cover that I've raised #70. I'll close this issue for now - please comment if you are still having  the original "another copy of the app is already running" issue.
