### ISSUE TITLE
FR: Option to add files from subfolders to main album

### ISSUE THREAD

**Issue by marcovanree** [ylexus/jiotty-photos-uploader#71]
photo folder
 - folder1
 - - folder2
 - - - photo1.jpg
 - - - photo2.jpg
 - - folder3
 - - - photo2.jpg
 - folder4

Like the example
all files in folder 1 including subfolders (folder2 and folder3) will be added to album "folder1" 

In this case you will have 2 albums, Folder1 and Folder4

**Comment by ylexus** [comment]
Should be doable. I'm on a holiday at the moment. Will work on this when I come back and find free time.

**Comment by marcovanree** [comment]
Nice then i will wait for that option :)

**Comment by ylexus** [comment]
@marcovanree, will this work for you? In your example, it'll do what you want if you set this new option to "2". "1" is the root level, i.e. the "photo folder", "2" is the level of "folder1" and "folder4" etc.

It sounds like I'll also need some graphic/picture, or simply a link to the wiki, to explain how this works.

![image](https://user-images.githubusercontent.com/6009806/92958876-e853cd80-f462-11ea-87a7-4b70be77c49b.png)

**Comment by marcovanree** [comment]
- folder1
 - - folder2
 - - - photo1.jpg
 - - - photo2.jpg
 - - folder3
 - - - photo3.jpg
 - folder4
- - photo4.jpg

So if i set it on 2, and if there is a root and photo folder then above example will create 2 albums ?
folder1 with images photo1.jpg, photo2.jpg, photo3.jpg and folder4 with image photo4.jpg ?

that's what i am looking for :)

If i point your program to the folder where all my album folders are, is it not easyer a checkbox include all subfolders from album folder ? But this works for me too, but maybe is that easyer to understand for users :)

**Comment by ylexus** [comment]
Yes, this is exactly what it will do.

Well, I could have a checkbox called "use only top level folders as albums" - this is definitely easier to understand, you are right. Still, some users will not understand anyway, I am sure :-). So I'll leave it as is and will have a link to the wiki with help. This whole thing is only for a very small amount of users.

**Comment by ylexus** [comment]
@marcovanree can you please:
1. translate some new resources marked with `#TODO translate` to Dutch? They are new phrases to support this new functionality, as well as some previous omissions - there are not many of these.
2. download this beta release https://github.com/ylexus/jiotty-photos-uploader/releases/tag/1.5.0-beta1 and test both this issue and #72? Please ignore the upgrade notification - I'll fix that later. The binary to run is `/Applications/Jiotty\ Photos\ Uploader.app/Contents/MacOS/Jiotty\ Photos\ Uploader`. If started without argument's it'll run a GUI. If started with at least one argument, it'll run a CLI. Add "-h" to get help on options. The CLI will use same preferences as GUI, i.e. to change preferences, run GUI, change preferences, and then the CLI will use them. 
3. let me know how it goes?

@axylee, can I please ask you again to translate phrases marked as `#TODO translate` to Chinese? Much appreciated.

**Comment by marcovanree** [comment]
Yes :) i'm going to test this

**Comment by ylexus** [comment]
Released in [1.5.0](https://github.com/ylexus/jiotty-photos-uploader/releases/tag/1.5.0)

**Comment by ylexus** [comment]
I'll leave it open for a while in case @axylee and @marcovanree you guys wanted to translate the new phrases :)

**Comment by marcovanree** [comment]
Works nice :D,
I have test this with different levels and works perfect.
Will make the translations tomorrow.

**Comment by ylexus** [comment]
@marcovanree @axylee would you be able to submit the translations - there is only a few new ones marked with #TODO. Thanks.

**Comment by marcovanree** [comment]
Sorry, I thought I already did :)

And 'Stop upload' is a good dutch translation :)

**Comment by ylexus** [comment]
@marcovanree thanks, released in 1.5.1
