### ISSUE TITLE
FR: a CLI option to run the program with parameters

### ISSUE THREAD

**Issue by marcovanree** [ylexus/jiotty-photos-uploader#72]
CLI option, then i can run it each night by a cron command to backup my photo folder

**Comment by ylexus** [comment]
Interestingly, the program can already be run as a CLI, but it's not easy to find the executable. Which OS are you interested in most, Mac?

**Comment by marcovanree** [comment]
I think something like linux, so i can run it on my home server where the photos are :)
But i can install a vm for it with ubuntu or windows or maybe a docker container.

More options that i can use, but how can i use it ? :)

**Comment by ylexus** [comment]
I am back from vacation, but too much stuff accumulated while I was away. I hope to get to this in a few days.

**Comment by ylexus** [comment]
@marcovanree I am going to release a preview version of the CLI, but it's time consuming (and currently manual) to release for each platform, how about I do it for macOS only (fastest for me as I work on macOS), and then if you like it I'll release for all platforms?

**Comment by marcovanree** [comment]
Ok, i can test it on the Mac then but i will not use it one the Mac.
On the Mac i use the gui interface.
I was thinking to set this up on my NAS or something :)

But i can still not use the program, waiting for ticket #71 because of my album structure on disk 
But i will be able to test stuff 👍

**Comment by ylexus** [comment]
I’ve almost finished with #71 too. I’ll ask you some questions about it too.

**Comment by ylexus** [comment]
Released in [1.5.0](https://github.com/ylexus/jiotty-photos-uploader/releases/tag/1.5.0)
