### ISSUE TITLE
macOS: standard About dialog is somehow accessible

### ISSUE THREAD

**Issue by marcovanree** [ylexus/jiotty-photos-uploader#73]

**Comment by marcovanree** [comment]
Can't find a donate option :)
But i can't use it for now but following.

Because my folder structure is different, see the other ticket :)

**Comment by ylexus** [comment]
The option is in the File-About dialog. It also appears on the upload screen where the progress bars are. Are you saying they are not there for you or they don’t work?

**Comment by marcovanree** [comment]
No Button there on a .Mac :)


Op ma 17 aug. 2020 om 13:46 schreef Alexey Yudichev <
notifications@github.com>

**Comment by ylexus** [comment]
It’s a link, not a button, to be clear. It’s very strange.  Can you send me a screenshot (via GitHub, email attachments don’t work apparently) of Apple menu - About Jiotty Photos Uploader, and of the upload screen? Which version are you using? The version is displayed in the About dialog. Very old versions don’t have the donate link or About menu. Ensure you download the latest.

**Comment by marcovanree** [comment]
<img width="603" alt="Schermafbeelding+2020-08-17+om+17 50 57" src="https://user-images.githubusercontent.com/3136441/90416135-5ef2ea80-e0b2-11ea-9c1e-6532c3758ab3.png">

this menu ?

**Comment by marcovanree** [comment]
but i didn't see a link on github or wiki ? :)
maybe you can put the link there too.

**Comment by ylexus** [comment]
Fascinating :). Maybe it’s a bug with Dutch translation. Will have a look when I get back from a holiday. Thanks for reporting. 

In the meantime, this is the donation link: http://paypal.me/yudichev

**Comment by ylexus** [comment]
Added the donation link to the wiki.

**Comment by ylexus** [comment]
@marcovanree I am really curious how you managed to open that dialog? I even recorded a video of me clicking Apple - About and seeing a completely different dialog, with the donation link on it: https://www.youtube.com/watch?v=MNi3Z01q76M

**Comment by marcovanree** [comment]
I will make a Video or More Screenshots about it this week 😄👍🏻

Op wo 26 aug. 2020 om 21:44 schreef Alexey Yudichev <
notifications@github.com>

**Comment by ylexus** [comment]
It may be enough to just tell me what you pressed/clicked to get to the About dialog in your screenshot... The dialog you see is the standard one JavaFX or package adds to a GUI macOS app. I though I overrode it, but clearly it's still there somehow.

**Comment by marcovanree** [comment]
Ah now the donation link is there, and more info text.
Maybe the translation was not set correctly the first startup ?

i haven't it installed again, so wierd :)

**Comment by marcovanree** [comment]
https://puu.sh/GopZD/388704fdf9.png

**Comment by ylexus** [comment]
You did manage to invoke that dialog somehow, and I know that it does exist in the app (see previous comments), so I’d like to keep it open for now. Do you have any idea what you might have done differently to get that about dialog?

**Comment by ylexus** [comment]
Is it likely that you still have the logs from the time you reproduced it? Will you be able to send me all the logs from `~/.jiottyphotosuploader/logs`? As a zip here or email to alexey@yudichev.net?

**Comment by marcovanree** [comment]
Found it and have seen it again after i did a logout.
But have seen it once, Just clicked "Jiotty Photos Uploader" => About Jiotty Photos Uploader

I will send you the logs today

**Comment by ylexus** [comment]
I found where the simple About dialog is coming from and I removed any references to it, also rationalising the way MacOS menu is built
