### ISSUE TITLE
i18n for MacOS standard menu items

### ISSUE THREAD

**Issue by ylexus** [ylexus/jiotty-photos-uploader#75]

**Comment by ylexus** [comment]
@axylee would you help again please? Just need a few translations in src/main/resources/menu_labels_zh* files. %s there is the name of the app "Jiotty Photos Uploader". Thanks!

**Comment by ylexus** [comment]
@marcovanree I wonder if you'll be able to help with Dutch translation of a few new phrases in the app? The previous person who used to help me with Dutch translation is off the radar now. If you can do it, then could you let me know you you're able to create GitHub pull requests and push the files, or instead prefer me to send you the text to be translated via GitHub comments like this one?

**Comment by marcovanree** [comment]
Yes i can help you with that, i am a php Developer so i know to work with
git and pull requests. Last week i had vacation but can help now.

Kind regards Marco

Op zo 30 aug. 2020 om 20:27 schreef Alexey Yudichev <
notifications@github.com>

**Comment by ylexus** [comment]
@marcovanree perfect! I actually found that some of the MacOS menus are not translated when I made a video for you in #73! Could you please translate the __values__ (i.e. text after the equals sign) in the following files:
1. src/main/resources/menu_labels_nl.properties
2. src/main/resources/i18n/Resources_nl.properties - ONLY for properties marked with a #TODO comment

Much appreciated!

**Comment by axylee** [comment]
> @axylee would you help again please? Just need a few translations in src/main/resources/menu_labels_zh* files. %s there is the name of the app "Jiotty Photos Uploader". Thanks!

Somehow I miss this notice , I will work on it these few days .

**Comment by marcovanree** [comment]
The dutch translations are almost done, i will make a PR today
