### ISSUE TITLE
Confusing error: "The upload was completed but failed to finalize or get the result"

### ISSUE THREAD

**Issue by ylexus** [ylexus/jiotty-photos-uploader#81]
Screenshot:
![image](https://user-images.githubusercontent.com/6009806/97032206-59ee6380-1559-11eb-8be4-a6ac4c5888ea.png)

Log:
[main.log](https://github.com/ylexus/jiotty-photos-uploader/files/5430824/main.log)

**Comment by ylexus** [comment]
Caused by https://github.com/google/java-photoslibrary/issues/39. I'll see if I can work around it to show a better error message.

**Comment by ylexus** [comment]
@marcovanree, @sngnr would you be able to translate a single new in your respective languages in under src/main/resources/i18n? 

```
#TODO translate
fatalUserCorrectableRemoteApiException.maybeEmptyFile=Empty file?
```

It's an error message that is printed when the file that the user tries to upload has a length of 0.

Thanks!

**Comment by marcovanree** [comment]
Sure, will do that tomorrow

**Comment by sngnr** [comment]
raised PR.

Sorry for the delay.

________________________________

**Comment by ylexus** [comment]
@marcovanree, would you be able to translate please?

**Comment by marcovanree** [comment]
Sorry was very busy last week. Will try this coming data.

Op ma 9 nov. 2020 om 23:05 schreef Alexey Yudichev <notifications@github.com

**Comment by ylexus** [comment]
Thanks @marcovanree and @sngnr for your translations, this can now be closed.
