### ISSUE TITLE
Add a tip on compressing after upload

### ISSUE THREAD

**Issue by martonthenagy** [ylexus/jiotty-photos-uploader#84]
As [grantpinkerton](https://github.com/grantpinkerton) commented on Apr 23 on [issue 22](https://github.com/ylexus/jiotty-photos-uploader/issues/22), it would be great that everyone should know that it is possible to recover their storage in a very easy way. I just copied that commend, and suggest to include it as a tip or in the faq, or wiki. 
This option will probably be removed or changed by Google on 2021.07.01.

"I was uploading a lot of images so for me it was easier to buy 100gb of space for a month, upload everything i needed, compress the images every day and then cancel my 100gb subscription. Hope that helps

How to Recover Storage on Google Photos

Go to photos.google.com, and click on the hamburger menu after signing in with the account.
Click on Settings, and switch to High Quality.
As soon as you do that, you will see a prompt “Recover XYZ.abc GB of storage by also compressing existing items (this can’t be undone).”
Check the box and click on the Confirm button.
Google Photos will start reducing the size of the photo of the uploaded images to match with High Quality.
You should see a message, “Compressing photos & videos to high quality.”
Depending on the size of the images and videos uploaded in Original quality, it may take time. You can close the windows and come back later to check how much storage was recovered. You can note down the amount of storage space left, which is available with the Original radio button option.

Note: You can only restore storage once a day."

Thank You for the great tool.

**Comment by ylexus** [comment]
Thanks, I've updated the wiki with this lifehack!
