### ISSUE TITLE
Error with special character ratio (∶)

### ISSUE THREAD

**Issue by Cantolla** [ylexus/jiotty-photos-uploader#85]
File names with the ratio (∶) character will be substituted with (?) character when uploaded with Jiotty Photos Uploader.

Character is correctly shown in the description of the image.

Uploading manually will result in a correct file name.

**Comment by ylexus** [comment]
Can I clarify where you see substituted characters? I just tried it on macOS and this is how it looks after the upload:
![image](https://user-images.githubusercontent.com/6009806/105559399-f7983100-5d08-11eb-9a73-ccfab18b33c7.png)

Tried under OpenSUSE Linux and it's the same. Can you provide a screenshot and/or more details about where you see the question mark?

**Comment by Cantolla** [comment]
If there is any confusion I am not using a colon, as apple considers it a prohibited character for file names. 
I am using a ratio character which looks similar to it.

As you can see in the screenshot the Description shows the ratio character correctly, but no in the file name. Works correctly when uploaded manually.

![Screenshot 2021-01-23 at 00 44 50](https://user-images.githubusercontent.com/77668116/105560511-3da6c200-5d14-11eb-9e13-dda4934f3334.jpg)

I am running Big Sur 11.1

**Comment by ylexus** [comment]
Actually, APFS on macOS allows for colons in file names, you can create such files in Terminal. It's just Finder does not allow to enter them nor it shows them properly.

Anyway, I've fixed this, will release new version shortly.

**Comment by Cantolla** [comment]
I was not aware of that, will keep in mind.

In any case I use Hazel to rename my photos and the number of files to rename would make it unfeasible to change again to colons.

Thank you very much for fixing the issue.
