### ISSUE TITLE
Possibility to personalize subfolder names

### ISSUE THREAD

**Issue by Cantolla** [ylexus/jiotty-photos-uploader#86]
Currently subfolders are named FOLDER : Subfolder : Subsubfolder.

Ability to choose to other formats such as FOLDER_Subfolder_Subsubfolder or FOLDER - Subfolder - Subsubfolder (For example)

**Comment by ylexus** [comment]
Done, new option in preferences is the delimiter to use between folder names. Will be in next release.

**Comment by Cantolla** [comment]
I appreciate the personalized capabilities.
Thank you very much!

**Comment by ylexus** [comment]
I'll keep it open, I as I'll need help with translations of new resources from other people. By the way, @Cantolla do you speak any other language than English? Would you mind help translating the app to your language?

**Comment by Cantolla** [comment]
I do, I am fluent in Spanish.
I'd be happy to help, email me with any translations you may need.
Do you want to translate to a specific language? Depending on the language I might know someone.

**Comment by ylexus** [comment]
Great, thanks. I've created issue #88 for this - let's continue there. I'll add instructions.
