### ISSUE TITLE
Translate to Spanish

### ISSUE THREAD

**Issue by ylexus** [ylexus/jiotty-photos-uploader#88]

**Comment by ylexus** [comment]
@Cantolla thanks for agreeing to help with Spanish translation. After you've helped with the initial bulk of translations, I may ask you to do one or two phrases, for example, I'll need new phrases for preferences dialog as a result of adding folder delimiter capability here.

I know you're new to GitHub, but this is where the world's developers build their (mostly open source) software and collaborate with other developers. To help with translation, you'll need to update some files and submit them to me, this is called "pull request". You can do this all in GitHub, no additional software needed. Basically, follow these steps (in a desktop browser):
1. first you need to "fork" this project - just click the fork button on the top right. 
2. in your fork project, go to Code tab and navigate to `src/main/resources/i18n/` folder, you'll see something like this:
![image](https://user-images.githubusercontent.com/6009806/105630231-e30a8480-5e3f-11eb-8e40-aee6a8bfe45f.png).
3. Click on the file names Resources_es.properties - this is the file I just created that will have Spanish translations.
4. Click on Edit icon.
5. Start translating by replacing the English text after each '=' sign with the Spanish equivalent. If you have any questions about the meaning or context of certain phrases, ask them here in this issue. 
    1. There is a 160 character limit for each line, so some lines are broken, such lines have a \ character - this means the text continues on the next line. In the app, the line will be joined and the \ symbol removed as if it was one line.
6. Once done, you can commit the change (need to provide short description, like "add Spanish translation"). You can keep editing and committing changes to this file, does not have to be all in one go.
7. Finally, create a pull request for your fork by following https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork.

Any questions - do ask, but hopefully it's not difficult. Thanks again!

**Comment by Cantolla** [comment]
I was playing around a bit to see how GitHub works, I think I got down the basics.

I do have one question.
![Screenshot 2021-01-24 at 18 09 13](https://user-images.githubusercontent.com/77668116/105637924-4ca28700-5e70-11eb-94f9-16eb48dbc793.jpg)
Which should I choose?

Doesn't seem to be that much to translate, I will get to it as soon as I have some free time!

**Comment by ylexus** [comment]
Use the first option, commit directly to master branch. Thanks!

**Comment by Cantolla** [comment]
Just translated something as a test. Please, confirm I did it correctly.
Last question, do I have to create a pull request any time I translate something or will it get updated automatically?

**Comment by ylexus** [comment]
Yes, all is correct. I've just realised that keeping a fork up to date is a complex thing that cannot be done in GitHub web interface. Can I ask you to commit what you've done so far and raise another pull request, and then try to do the edits directly in this repository, and not in your fork? I've just invited you to become a collaborator, I think once you've done it, you will be able to create pull requests from your branch to master. 
So step 1 is not required, step 2 needs to be done on the original repo, and not on the fork, on step 6 you'll need to create a new branch, call it `feature/spanish-translation`, and step 7 changes to be https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request.

Sorry to confuse things initially.

**Comment by ylexus** [comment]
To answer your question about the pull request, you do not need to create a new one if the previous one has not yet been merged (i.e. accepted and deleted). If the previous one has already been merged, then you'll have to create a new one.

What I'll do is I'll try this whole journey using a different GitHub account and see if it's straightforward.

**Comment by ylexus** [comment]
@Cantolla all works - please forget your fork (commit all pending work and create pull request, wait until I merge it and can delete your fork after), and continue translating on this repository directly. A little easier.

**Comment by Cantolla** [comment]
Appreciate the clear instructions.
Could not commit to the master branch (Option was blocked) but I think I did it correctly.
Just did another small test.
Please confirm everything is set correctly.

**Comment by ylexus** [comment]
@Cantolla I left a comment on the pull request
