### ISSUE TITLE
Does Jiotty honour star rating EXIF data?

### ISSUE THREAD

**Issue by keiranharris** [ylexus/jiotty-photos-uploader#95]
Hey, great work on this code. Not really an ‘issue’ as such, but more of a question (that may turn into a feature request). 

I am hoping to use your program before the june quota kicks in. I was wondering / hoping that your code handles translating star ratings embedded in images EXIF data.... and if a star exists (any would do, 1 star, 2 star.... 5 star), mark it as a FAVOURITE in google photos ? Ive spent a lot of time over the years flagging my fav pics as such and would need to preserve that on the upload. 

Thanks!

**Comment by ylexus** [comment]
Hi. There is no way to mark a photo as favourite using Google Photos API. All I can try to do is add such photo to a specific album. I don't see though how you can then mark all photos in the album as favourites - can't do it in the app at least.

**Comment by keiranharris** [comment]
Thanks for getting back to me and filling me in on the API limitations. 

The folder thing is a good idea - you got me thinking i could actually do this myself..... [although my starred pics are currently scattered in amongst the normal pics in any given folder/event, so id have to do exporting of just starred pics to a given folder and then upload that with your program. .... but google’s duplicate photo detection may later trip me up... eg. If i do this exported favourites folder first, then the pics in their original folder will fail when i upload the main folders structure]

.... do we know how that duplicate algorithm works? Ie if i add a watermark or something will it sidestep the detection? Id ideally want both:
1/ the main folder containing all pics - inc favs
2/ fav pics from that event somehow flagged. 

Appreciate your brainpower! 
Thanks 
Keiran.

**Comment by ylexus** [comment]
It won’t trip, it will actually do what you want, i.e. you’ll have a single photo in two albums. When you upload a duplicate, it succeeds, it just doesn’t create a duplicate. Hope it makes sense.

**Comment by ylexus** [comment]
There’s a FAQ entry about duplicates - please read.

**Comment by keiranharris** [comment]
Right, so i assume you mean this >>> “ If a photo or video has been uploaded by this app, and you selected not to resume uploads, Jiotty will upload it again, but Google Photos will match it to the previously uploaded photo, and no duplicate will be created.”  So given what you say, i assume the first folder upload which creates an album will have the pic, and then any subsequent albums that also have that would be a pointer to the first pic. Is that what you mean? Ill have a fiddle on the weekend. Thanks again!

**Comment by ylexus** [comment]
Yes, all correct. You will end up with a single photo in more than one album.
